### ISSUE TITLE
'column' に指定した場合の挙動

### ISSUE THREAD

**Issue by inutano** [togostanza/metastanza#32]
hash-table の仕様についてお尋ねです。（他のテーブル系も該当するかも）

現状では `column` に指定を入れると、指定したカラムだけが表示されます。指定がないと、データの全てのフィールドがカラムとして表示される仕様であるという認識です。しかし、この仕様だと「データのフィールド数は多いが、カラムで書式を指定したいのは一部のみ」という場合に、書式をいじりたいカラム以外も全て書く必要があって面倒です。

- 基本的にデータは全て出す
- `column` で書式が指定された場合は上書きする

という挙動にできませんか？

コードベースとしてはこの部分かなとおもいます。
https://github.com/togostanza/metastanza/blob/ff1b61f91a4e652e39a3abd8c9af24ff8f55c8eb/stanzas/hash-table/index.js#L7

cc. @ktym @reika0717 @TerueTakatsuki

**Comment by moriya-dbcls** [comment]
別のフィールドのURLとしてのみ使ったりする場合は出てほしく無いですね。あと column 指定しないで自動で表示する場合は、表示の順番が js で取り出した順番（js の実装依存）になってしまうので、最低 id のリストは column に書くしか無いのが現状です

**Comment by inutano** [comment]
なるほど、、、

**Comment by moriya-dbcls** [comment]
MetaStanza 用のデータ構造の共通化を行う上で、テーブルヘッダが column に移動した経緯があるので、、、テーブルヘッダはみんな書くよね、というそんな流れ、、

**Comment by inutano** [comment]
歴史的経緯了解です、metastanzaの側のattributeは変えずに動的に流すdata-urlを変えるみたいなことをしているとカラムの指定つらいな〜〜という感じだったんですが、jsでゴリ押しします！！

**Comment by inutano** [comment]
（そうするとじゃあ逆にカラムが指定されていないと全部出るという挙動に違和感が）
